#!/bin/bash
. ./lib

clonedir=$DIRUSER/.dotfiles/hypr-dot

if (confirm "Do you want to authorize $clonedir with github token key?"); then
  username=$(dialog --backtitle "$apptitle" --title "Authorize hypr-dot repo" --inputbox "Enter your github user name :" 0 0 3>&1 1>&2 2>&3)
  token=$(dialog --backtitle "$apptitle" --title "Authorize hypr-dot repo" --inputbox "Enter your github token key :" 0 0 3>&1 1>&2 2>&3)
  clear
  cd $clonedir
  git remote set-url origin https://$username:$token@github.com/$username/hypr-dot.git
  cd ..
fi

exit 0
