#!/bin/bash
. ./lib

options=()
options+=(
	"Yay" ""
	"Paru" ""
)

sel=$(dialog --backtitle "$apptitle" --title "Aur Helper :" --cancel-button "Back" --menu "" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

case $sel in
Yay) script update/aur/yay ;;
Paru) script update/aur/paru ;;
esac

exit 0
