#!/bin/bash
. ./lib

options=()
options+=(
	"Virt Manager" ""
)
sel=$(dialog --backtitle "$apptitle" --title "Other Applications :" --cancel-button "Back" --menu "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

case $sel in
"Virt Manager")
	message "Script will open neovim editor. \nTo quit press ":q""
	nvim install/apps/others/vm
	# message "This is an autoscript. \nIf you confirm will start installation."
	if (confirm "Do you want to start Virt manager installation \n "); then
    clear
		script install/apps/others/vm
	fi
	;;
esac

exit 0
