#!/bin/bash
. ./lib

options=()
options+=(
	"Office" ""
	"Internet" ""
  "Software" ""
	"System" ""
	"Others" ""
)

defaultitem=""
sel=$(dialog --backtitle "$apptitle" --title "Applications :" --default-item "$defaultitem" --cancel-button "Back" --menu "" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
	exit 1
fi

sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
"Office") script install/office/office ;;
"Internet") script install/internet/net ;;
"Software") menu install/software/menu ;;
"System") script install/system/system ;;
"Others") script install/others/menu ;;
esac

exit 0
