#!/bin/bash
. ./lib

options=()
options+=(
	"firefox" "" on
	"thunderbird" "" on
	"wget" "" off
	"uget" "" off
	"transmission-gtk" "" off
	"transmission-qt" "" off
)
sel=$(dialog --backtitle "$apptitle" --title "Internet applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
	case $itm in
	"firefox") choosepkg "firefox-i18n-" ;;
	"thunderbird") choosepkg "thunderbird-i18n-" ;;
	esac
done

exit 0
