#!/bin/bash
. ./lib

options=()
options+=(
	"Virt Manager" ""
)
sel=$(dialog --backtitle "$apptitle" --title "Other Applications :" --cancel-button "Back" --menu "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

case $sel in
  "Virt Manager")
    script install/others/vm
    ;;
esac

exit 0
