#!/bin/bash
. ./lib

options=()
options+=(
"Oh my zsh" ""
"Hyprland Dotfiles" ""
)
sel=$(dialog --backtitle "$apptitle" --title "Dotfiles :" --cancel-button "Back" --menu "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

case $sel in
  "Oh my zsh") script config/dotfiles/ohmyzsh ;;
  "Hyprland Dotfiles") menu config/dotfiles/hypr/menu ;; 
esac

exit 0
