#!/bin/bash
. ./lib

options=()
options+=(
"Wayland" ""
"X11" ""
)
defaultitem=""
sel=$(dialog --backtitle "$apptitle" --title "Nvidia Drivers :" --default-item "$defultitem" --cancel-button "Back" --menu "" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi
sed i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
"Wayland") script install/drivers/wayland ;;
"X11") script install/drivers/x11 ;;
esac

exit 0
