#!/bin/bash
. ./lib

options=()
options+=(
	"wireplumber" "" on
	"pipewire" "" on
  "pipewire-alsa" "" on
  "pipewire-pulse" "" on
	"pipewire-jack" "" on
)
sel=$(dialog --backtitle "$apptitle" --title "Multimedia :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	# "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"
