#!/bin/bash
. ./lib

options=()
options+=(
	"libva" "" on
	"nvidia-open-dkms" "" on
	"nvidia-utils" "" on
	"lib32-nvidia-utils" "" on
	"opencl-nvidia" "" on
	"lib32-opencl-nvidia" "" on
	"nvidia-settings" "" on
	"libva-nvidia-driver-git" "(AUR)" on
)
sel=$(dialog --backtitle "$apptitle" --title "Nvidia for wayland :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	"libva-nvidia-driver-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

# NVIDIA modules in mkinitcpio
sudo sed -i "s/MODULES=()/MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm kvm kvm_intel)/g" /etc/mkinitcpio.conf
sudo mkinitcpio -P
# Additional steps
sudo echo -e "options nvidia-drm modeset=1" | sudo tee -a /etc/modprobe.d/nvidia.conf
# Blacklist nouveau
sudo echo -e "blacklist nouveau" | sudo tee -a /etc/modprobe.d/nouveau.conf

exit 0
