#!/bin/bash
. ./lib

options=()
options+=(
	"nvidia" "" off
	"nvidia-dkms" "" off
	"nvidia-open-dkms" "" on
	"nvidia-utils" "" on
	"lib32-nvidia-utils" "" on
	"opencl-nvidia" "" on
	"lib32-opencl-nvidia" "" on
	"nvidia-settings" "" on
	"libva" "" on
)
sel=$(dialog --backtitle "$apptitle" --title "Nvidia for X11 :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	# "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

exit 0
