#!/bin/bash
. ./lib

options=()
options+=(
	"gparted" "Partition manager" off
	"bleachbit" "Profile cleaner" off
	"stacer-bin" "(AUR)" off
	"openrgb-bin" "(AUR)" off
	"lm_sensors" "" on
	"lib32-lm_sensors" "" on
	"i2c-tools" "" on
)

sel=$(dialog --backtitle "$apptitle" --title "System applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	"stacer-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"openrgb-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

if [ -f /usr/bin/sensors-detect ]; then
	sudo sensors-detect --auto
fi

exit 0
