#!/bin/bash
. ./lib

options=()
options+=(

  "sshfs" "" off
  "openssh" "" on
  "samba" "" on
  "man-db" "" on
  "man-pages" "" on
  "dialog" "" off
	"lm_sensors" "" off
	"lib32-lm_sensors" "" off
	"i2c-tools" "" off
)

sel=$(dialog --backtitle "$apptitle" --title "System applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

if [ -f /usr/bin/sensors-detect ]; then
	sudo sensors-detect --auto
fi

exit 0
