#!/bin/bash
#!/bin/bash
. ./lib

options=()
options+=(
	"baobab" "" on
	"eog" "" on
	"evince" "" on
	"file-roller" "" on
	"gedit" "" on
	"gnome-backgrounds" "" on
	"gnome-calculator" "" on
	"gnome-calendar" "" on
	"gnome-characters" "" on
	"gnome-color-manager" "" on
	"gnome-control-center" "" on
	"gnome-disk-utility" "" on
	"gnome-font-viewer" "" on
	"gnome-keyring" "" on
	"gnome-logs" "" on
	"gnome-menus" "" on
	"gnome-photos" "" on
	"gnome-remote-desktop" "" on
	"gnome-session" "" on
	"gnome-settings-daemon" "" on
	"gnome-shell" "" on
	"gnome-shell-extensions" "" on
	"gnome-terminal" "" on
	"gnome-software" "" on
	"gnome-themes-extra" "" on
	"gnome-user-docs" "" on
	"gnome-user-share" "" on
	"grilo-plugins" "" on
	"mutter" "" on
	"nautilus" "" on
	"sushi" "" on
	"tracker" "" on
	"tracker3-miners" "" on
	"tracker-miners" "" on
	"xdg-user-dirs-gtk" "" on
	"gnome-tweaks" "" on
	"gnome-sudoku" "" on
	"gnome-sound-recorder" "" on
	"gnome-nettool" "" on
	"gnome-mines" "" on
	"gnome-mahjongg" "" on
	"gnome-chess" "" on
	"ghex" "" on
	"gnome-software-packagekit-plugin" "" on
	"packagekit" "" on
)

sel=$(dialog --backtitle "$apptitle" --title "Gnome :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	# "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

#for forced wayland support (gdm 42 rc version)
#sudo ln -s /dev/null /etc/udev/rules.d/61-gdm.rules

exit 0
