#!/bin/bash
. ./lib

options=()
options+=(
  "hyprland" "" on
  "hyprland-git" "(AUR)" off
  "qt5ct" "" off
  "qt5ct-kde" "(AUR)" on
  "qt5-wayland" "" on
  "qt6ct" "" off
  "qt6-wayland" "" on
  "gtk3" "" on
  "cliphist" "" on
  "waybar" "" on
  "waybar-updates" "(AUR)" on
  "wttrbar" "(AUR)" off
  "nwg-look-bin" "(AUR)" off
  "lxappearance" "" off
	"lightly-boehs-git" "(AUR)" off
	"lightly-git" "(AUR)" on
  "kitty" "" on
  "wofi" "" off
  "rofi" "" on
  "mako" "" on
  "swappy" "" on
  "grim" "" on
  "slurp" "" on
  "swaybg" "" on
  "playerctl" "" on
  "polkit-kde-agent" "" off
  "polkit-gnome" "" on
  "swww" "(AUR)" on
  "swaylock-effects" "(AUR)" on
  "swayidle" "(AUR)" on
  "wlogout" "(AUR)" on
  "imv" "" on
  "pamixer" "" on
  "pavucontrol" "" on
  "blueman" "" on
  "iwgtk" "(AUR)" on
  "xdg-desktop-portal-hyprland" "" on
  "xdg-desktop-portal-gtk" "" on
)

sel=$(dialog --backtitle "$apptitle" --title "Hyprland :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
  # "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "hyprland-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "qt5ct-kde") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "waybar-updates") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "wttrbar") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "nwg-look-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"lightly-boehs-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"lightly-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "swww") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "swaylock-effects") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "swayidle") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "wlogout") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "iwgtk") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  *) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
