#!/bin/bash
. ./lib

read -n1 -rp "Would you like to start Hyprland installation and install neccesery packages? (y/n) " hyprins
echo
if [[ $hyprins =~ ^[Yy]$ ]]; then
	# Hyprland and additional packages
	echo "Hyprland installation started..."
	# sudo pacman -S --needed hyprland
  	yay -S --needed hyprland-nvidia
	#
	sudo pacman -S --needed qt5ct qt5-wayland qt6ct qt6-wayland
	yay -S --needed waybar-hyprland-git nwg-look-bin
	#
	sudo pacman -S --needed kitty wofi mako swappy grim slurp swaybg playerctl polkit-kde-agent
	yay -S --needed swww swaylock-effects swayidle wlogout
	#
	sudo pacman -S --needed imv pamixer pavucontrol blueman network-manager-applet

	# XDG-DESKTOP
	read -n1 -rep "Wolud you like to install XDG-desktop-portal for Hyprland (y/n) " xdg_hypr
	if [[ $xdg_hypr =~ ^[Yy]$ ]]; then
		printf "Installing xdg-desktop-portal-hyprland"
		sudo pacman -S --needed xdg-desktop-portal-hyprland
		sudo pacman -R xdg-desktop-portal-gnome xdg-desktop-portal-gtk
	else
		echo "XDG-desktop-portal for Hyprland won't install"
	fi
else
	echo "Hyprland and required packages not installed..."
fi

# Set up SDDM
read -n1 -rep "Would you like to set SDDM? (y,n)" SDDM
if [[ $SDDM =~ ^[Yy]$ ]]; then
	echo -e "Setting up the login screen."
	sddm_conf_dir=/etc/sddm.conf.d
	if [ ! -d "$sddm_conf_dir" ]; then
		printf "$sddm_conf_dir not found, creating...\n"
		sudo mkdir "$sddm_conf_dir"
		echo -e "[Theme]\nCurrent=sugar-candy" | sudo tee "$sddm_conf_dir/10-theme.conf"
		sudo cp $DIR/dotfiles/config/wayland/extra/sddm/sddm.conf "$sddm_conf_dir/"
	fi
	echo -e "Setting up sugar-candy theme."
	sugar_candy_dir=/usr/share/sddm/themes/sugar-candy
	if [ ! -d "$sugar_candy_dir" ]; then
		printf "$sugar_candy_dir not found, creating...\n"
		sudo tar -xzvf $DIR/dotfiles/config/wayland/extra/sddm/sugar-candy/sugar-candy.tar.gz -C /usr/share/sddm/themes/
		sudo cp $DIR/dotfiles/config/wayland/extra/sddm/sugar-candy/theme.conf "$sugar_candy_dir/"
		sudo cp $DIR/dotfiles/config/wayland/extra/sddm/sugar-candy/background.jpg "$sugar_candy_dir/Backgrounds/"
	fi
else
	echo "SDDM isn't set"
fi
