#!/bin/bash
. ./lib

options=()
options+=(
	"hyprland" "" off
	"hyprland-nvidia" "(AUR)" on
	"qt5ct" "" on
	"qt5-wayland" "" on
	"qt6ct" "" on
	"qt6-wayland" "" on
	"waybar-hyprland-git" "(AUR)" on
	"nwg-look-bin" "(AUR)" on
	"kitty" "" on
	"wofi" "" on
	"mako" "" on
	"swappy" "" on
	"grim" "" on
	"slurp" "" on
	"swaybg" "" on
	"playerctl" "" on
	"polkit-kde-agent" "" on
	"swww" "(AUR)" on
	"swaylock-effects" "(AUR)" on
	"swayidle" "(AUR)" on
	"wlogout" "(AUR)" on
	"imv" "" on
	"pamixer" "" on
	"pavucontrol" "" on
	"blueman" "" on
	"network-manager-applet" "" on
	"xdg-desktop-portal-hyprland" "" on
)

sel=$(dialog --backtitle "$apptitle" --title "Hyprland :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	# "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"hyprland-nvidia") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"waybar-hyprland-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"nwg-look-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"swww") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"swaylock-effects") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"swayidle") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"wlogout") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

# remove other xdg-desktop-portal
if (confirm "Do you want to remove other xdg-desktop-portal \n "); then
	sudo pacman -R xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi

exit 0
