#!/bin/bash
. ./lib

if lspci | grep -E "(VGA|3D)" | awk '/AMD/'; then
  gpumodule1="amdgpu radeon"
else
  gpumodule1=""
fi

if lspci | grep -E "(VGA|3D)" | awk '/NVIDIA/'; then
  gpumodule2="nvidia nvidia_modeset nvidia_uvm nvidia_drm"
else
  gpumodule2=""
fi

if [ $gpumodule1 == "" ]; then
  gpumodule=$gpumodule2
elif [ $gpumodule2 == "" ]; then
  gpumodule=$gpumodule1
else
  gpumodule="$gpumodule1 $gpumodule2"
fi

# modify mkinitcpio.conf
sudo sed -i "s/MODULES=()/MODULES=($gpumodule)/g" /etc/mkinitcpio.conf

if [ $gpumodule2 != "" ]; then
  # i think not needed with supergfxctl
  # Blacklist nouveau
  # printf "blacklist nouveau" | sudo tee /etc/modprobe.d/nouveau.conf
fi

sudo mkinitcpio -P
