#!/bin/bash

part1=$(findmnt -no UUID -T /swapfile)
part2=$(filefrag -v /swapfile | awk '$1=="0:" {print substr($4, 1, length($4)-2)}')
part3=$(cat /etc/kernel/cmdline)
part4="quiet systemd.unit=graphical.target nvidia-drm.modeset=1"
hbrnation="$part3 $part4 resume=UUID=$part1 resume_offset=$part2"
printf "%s" "$hbrnation" | sudo tee /etc/kernel/cmdline

sed -i -e 's/fsck/resume fsck/g' /etc/mkinitcpio.conf
# sudo sed -Ei 's/^(HOOKS=\([^\)]*)\)/\1 resume)/' /etc/mkinitcpio.conf

mkinitcpio -P
