#!/bin/bash
. ./lib

if [ ! -d $cachedir/dotfiles ]; then
  git clone https://github.com/drpars/dotfiles.git
fi

### Copy Config Files ###
read -n1 -rep "Would you like to copy config files? (y,n) " CFG
if [[ $CFG =~ ^[Yy] ]]; then
  echo -e "Copying config files..."

  # copy the HyprV directory
  cp -R $cachedir/dotfiles/HyprV4-SolDoesTech/HyprV ~/.config/

  #set the measuring unit
  echo -e "Attempring to set mesuring unit..."
  if locale -a | grep -q ^en_US; then
    echo -e "Setting mesuring system to imperial..."
    ln -sf ~/.config/HyprV/waybar/conf/mesu-imp.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc
    sed -i 's/SET_MESU=""/SET_MESU="I"/' ~/.config/HyprV/hyprv.conf
  else
    echo -e "Setting mesuring system to metric..."
    sed -i 's/SET_MESU=""/SET_MESU="M"/' ~/.config/HyprV/hyprv.conf
    ln -sf ~/.config/HyprV/waybar/conf/mesu-met.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc
  fi

  # Setup each appliaction
  # check for existing config folders and backup
  for DR in hypr kitty mako swaylock waybar wlogout wofi; do
    DIRPATH=~/.config/$DR
    if [ -d "$DIRPATH" ]; then
      echo -e "Config for $DR located, backing up."
      mv $DIRPATH $DIRPATH-back
      echo -e "Backed up $DR to $DIRPATH-back."
    fi

    # make new empty folders
    mkdir -p $DIRPATH
  done

  # link up the config files
  echo -e "Setting up the new config..."
  cp ~/.config/HyprV/hypr/* ~/.config/hypr/
  ln -sf ~/.config/HyprV/kitty/kitty.conf ~/.config/kitty/kitty.conf
  ln -sf ~/.config/HyprV/mako/conf/config-dark ~/.config/mako/config
  ln -sf ~/.config/HyprV/swaylock/config ~/.config/swaylock/config
  ln -sf ~/.config/HyprV/waybar/conf/v4-config.jsonc ~/.config/waybar/config.jsonc
  ln -sf ~/.config/HyprV/waybar/style/v4-style-dark.css ~/.config/waybar/style.css
  ln -sf ~/.config/HyprV/wlogout/layout ~/.config/wlogout/layout
  ln -sf ~/.config/HyprV/wofi/config ~/.config/wofi/config
  ln -sf ~/.config/HyprV/wofi/style/v4-style-dark.css ~/.config/wofi/style.css

  # add the Nvidia env file to the config (if needed)
  if [[ "$ISNVIDIA" == true ]]; then
    echo -e "\nsource = ~/.config/hypr/env_var_nvidia.conf" >>~/.config/hypr/hyprland.conf
  fi

  # stage the .desktop file
  # sudo cp $cachedir/HyprV4-SolDoesTech/Extras/hyprland.desktop /usr/share/wayland-sessions/

  # setup the first look and feel as dark
  # xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita-dark"
  # xfconf-query -c xsettings -p /Net/IconThemeName -s "Papirus-Dark"
  # gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
  # gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
  # cp -f ~/.config/HyprV/backgrounds/v4-background-dark.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg
fi
