#!/bin/bash
. ./lib

backupdir=$DIRUSER/.dotfiles/backup
clonedir=$DIRUSER/.dotfiles/hypr-dot
configfiles="$(ls $clonedir/config)"
pictrs=$(xdg-user-dir PICTURES)
homefiles="
  .gitconfig
  .gtkrc-2
  .zshrc
  "
read -rep "Do do you want to copy dotfiles ? (y,n)" copydot
if [[ $copydot =~ ^[yY]$ ]]; then
  mkdir -p $backupdir
  mkdir -p $clonedir

  if [ -d $clonedir ]; then
    rm -rf $clonedir
    git clone https://github.com/drpars/hypr-dot.git $clonedir
  fi

  for sel in $configfiles; do
    if [ -d $DIRUSER/.config/$sel ]; then
      mv $DIRUSER/.config/$sel $backupdir
    elif [ -L $DIRUSER/.config/$sel ]; then
      rm $DIRUSER/.config/$sel
    fi
  done
  # dotfiles
  ln -sr $clonedir/config/* $DIRUSER/.config
  # $HOME files
  for sel in $homefiles; do
    if [ ! -f $DIRUSER/$sel ]; then
      ln -sr $clonedir/$sel $DIRUSER
    else
      mv $DIRUSER/$sel $backupdir
      ln -sr $clonedir/$sel $DIRUSER
    fi
  done
  printf "%s\n" "" "Config files are copied."
fi

read -rep "Do you want to authorize $clonedir (hypr-dot repo) with github token key ? (y,n) : " auth
if [[ $auth =~ ^[yY]$ ]]; then
  read -rep "Enter your github user name : " username
  read -rep "Enter token key : " token
  cd $clonedir
  git remote set-url origin https://$username:$token@github.com/$username/hypr-dot.git
  cd ..
fi
# other dotfles for hyprland
read -rep "Do you want to copy user themes ? (y,n) " theme
if [[ $theme =~ ^[yY]$ ]]; then
  if [ ! -d $DIRUSER/.themes ]; then
    mkdir $DIRUSER/.themes
  fi
  tar -xzvf $clonedir/themes/Tokyonight-Dark-BL-LB.tar.gz -C $DIRUSER/.themes/
  tar -xzvf $clonedir/themes/HeroicTheme.tar.gz -C $DIRUSER/.themes/
fi

read -rep "Do you want to copy wallpapers ? (y,n) " wallpaper
if [[ $wallpaper =~ ^[yY]$ ]]; then
  cp -r $clonedir/Wallpaper $pictrs
fi

read -rep "Do you want to set sddm settings & theme ? (y,n) " sdm
if [[ $sdm =~ ^[yY]$ ]]; then
  if [ -f /usr/bin/sddm ]; then
    sddm_conf_dir=/etc/sddm.conf.d
    if [ ! -d "$sddm_conf_dir" ]; then
      printf "$sddm_conf_dir not found, creating...\n"
      sudo mkdir "$sddm_conf_dir"
    fi
    echo -e "[Theme]\nCurrent=sugar-candy" | sudo tee "$sddm_conf_dir/10-theme.conf"
    sudo cp $clonedir/sddm/sddm.conf "$sddm_conf_dir/"
    sugar_candy_dir=/usr/share/sddm/themes/sugar-candy
    if [ ! -d "$sugar_candy_dir" ]; then
      printf "$sugar_candy_dir not found, creating...\n"
      sudo tar -xzvf $clonedir/sddm/sugar-candy/sugar-candy.tar.gz -C /usr/share/sddm/themes/
      sudo cp $clonedir/sddm/sugar-candy/theme.conf "$sugar_candy_dir/"
      sudo cp $clonedir/sddm/sugar-candy/background.jpg "$sugar_candy_dir/Backgrounds/"
    fi
  else
    message "Sddm not installed. \nFirstly install sddm!"
    if (confirm "Do you want to jump Display Manager installation ? \n "); then
      menu install/displaymngr/menu
    fi
  fi
fi
