#!/bin/bash
. ./lib

options=()
options+=(
	"Samba settings" ""
	"Disk settings" ""
	"Hibernation settings" ""
	"Copy dotfiles" "Hyprland"
)
sel=$(dialog --backtitle "$apptitle" --title "Settings :" --cancel-button "Back" --menu "" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

case $sel in
"Samba settings")
	message "Script will open neovim editor. \nTo quit press ":q""
	nvim config/samba
	if (confirm "Do you want to apply samba script ?"); then
		clear
		script config/samba
		pressanykey
	fi
	;;
"Disk settings")
	message "Script will open neovim editor. \nTo quit press ":q""
	nvim config/disks
	if (confirm "Do you wanto apply disks script ?"); then
		clear
		script config/disks
		pressanykey
	fi
	;;
"Hibernation settings")
	message "Script will open neovim editor. \nTo quit press ":q""
	nvim config/disks
	if (confirm "Do you want to apply hibernation script ?"); then
		clear
		script config/hibernation
		pressanykey
	fi
	;;
"Copy dotfiles")
	if (confirm "Do you want to copy all dotfiles ? \n "); then
		clear
		echo "Copying dotfiles..."
		git clone https://gitlab.com/drpars/dotfiles.git
    # hypr
		cp -r $DIR/dotfiles/config/wayland/{hypr,mako,scripts,swaylock,waybar,wlogout,wofi} $DIRUSER/.config/
    # user files
		cp $DIR/dotfiles/.zshrc $DIRUSER/
		cp $DIR/dotfiles/.gtkrc-2.0 $DIRUSER/
		# ~/.config
    cp $DIR/dotfiles/config/kdeglobals $DIRUSER/.config/
		cp -r $DIR/dotfiles/config/{btop,gtk-3.0,imv,kitty,mc,Mousepad,nwg-look,qt5ct,Thunar,xfce4,xsettingsd} $DIRUSER/.config/
		cp $DIR/dotfiles/scripts/* $DIRUSER/.config/scripts/
		# make executable scripts files
		chmod +x $DIRUSER/.config/scripts/*
		chmod +x $DIRUSER/.config/scripts/waybar/*
		chmod +x $DIRUSER/.config/hypr/xdg-portal-hyprland
		# wallpapers
		cp -r $DIR/dotfiles/Wallpaper $DIRUSER/Resimler/
	else
		message "Nothing copied \n "
	fi
	;;
esac

exit 0
