#!/bin/bash
. ./lib

options=()
options+=(
  "Time & keymap settings" ""
  "Samba settings" ""
  "Disk settings" ""
  "NVIDIA settings" ""
  "Hibernation settings" ""
  "Neovim configs" ""
  "Remove neovim configs" ""
  "Hyprland-Dotfiles" ""
)
sel=$(dialog --backtitle "$apptitle" --title "Settings :" --cancel-button "Back" --menu "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

case $sel in
"Time & keymap settings")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/time
  if (confirm "Do you want to apply time script ?"); then
    clear
    script config/time
    pressanykey
  fi
  ;;
"Samba settings")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/samba
  if (confirm "Do you want to apply samba script ?"); then
    clear
    script config/samba
    pressanykey
  fi
  ;;
"Disk settings")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/disks
  if (confirm "Do you want to apply disks script ?"); then
    clear
    script config/disks
    pressanykey
  fi
  ;;
"NVIDIA settings")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/nvidia
  if (confirm "Do you wanto apply nvidia script ?"); then
    clear
    script config/nvidia
    pressanykey
  fi
  ;;
"Hibernation settings")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/hibernation
  if (confirm "Do you want to apply hibernation script ?"); then
    clear
    sscript config/hibernation
    pressanykey
  fi
  ;;
"Neovim configs")
  if (confirm "Do you want to copy nvim config ? \n "); then
    clear
    script config/nvim
  else
    message "Nothing copied \n "
  fi
  ;;
"Remove neovim configs")
  if (confirm "Do you want to remove nvim ? \n "); then
    clear
    rm -rf ~/.config/nvim
    rm -rf ~/.local/share/nvim
    rm -rf ~/.cache/nvim
    message "Neovim removed. \n "
  fi
  ;;
"Hyprland-Dotfiles")
  message "Script will open neovim editor. \nTo quit press ":q""
  nvim config/hypr-dot
  if (confirm "Do you want to copy all dotfiles ? \n "); then
    clear
    script config/hypr-dot
    pressanykey
  else
    message "Nothing copied \n "
  fi
  ;;
esac

exit 0
