#!/bin/bash
. ./lib

if lspci | grep -E "(VGA|3D)" |  awk '/AMD/';then
  gpumodule1="amdgpu radeon"
else
  gpumodule1=""
fi

if lspci | grep -E "(VGA|3D)" |  awk '/NVIDIA/';then
  gpumodule2="nvidia nvidia_modeset nvidia_uvm nvidia_drm"
else
  gpumodule2=""
fi
gpumodule="$gpumodule1 $gpumodule2"

# NVIDIA modules in mkinitcpio
sudo sed -i "s/MODULES=()/MODULES=($gpumodule kvm kvm_$cputype)/g" /etc/mkinitcpio.conf
sudo mkinitcpio -P
# Additional steps
sudo echo -e "options nvidia-drm modeset=1" | sudo tee -a /etc/modprobe.d/nvidia.conf
# Blacklist nouveau
sudo echo -e "blacklist nouveau" | sudo tee -a /etc/modprobe.d/nouveau.conf

