#!/bin/bash
. ./lib

# only tty5 will patch

instpkg kmscon-patched-git

if [ ! -d /etc/kmscon ]; then
  sudo mkdir /etc/kmscon
fi

# kmscon settings
printf "%s\n" "" "font-name=Jet Brains Mono Nerd Font" "font-size=10" "font-dpi=128" | sudo tee /etc/kmscon/kmscon.conf
# disable default tty5
svcdisable getty@tty5.service
# enable patch fot tty5
svcenable kmsconvt@tty5.service
