#!/bin/bash

# only tty5 will patch
#
yay -S --needed kmscon-patched-git

# checking fonts
touch fnts
fnt=$(ls /usr/share/fonts/TTF <fnts)

if grep UbuntuMonoNerd fnts; then
  sudo pacman -S ttf-ubuntu-mono-nerd
else
  echo "UbuntuMonoNerd Font is already installed"
fi

rm fnts

if [ ! -d /etc/kmscon ]; then
  sudo mkdir /etc/kmscon
fi
# kmscon settings
printf "%s\n" "" "font-name=Jet Brains Mono Nerd Font" "font-size=10" "font-dpi=128" | sudo tee /etc/kmscon/kmscon.conf
# disable default tty5
sudo systemctl disable getty@tty5.service
# enable patch fot tty5
sudo systemctl enable kmsconvt@tty5.service
