#!/bin/bash
. ./lib

sudo pacman -S --needed samba avahi
sudo cp $DIR/config/smb.conf /etc/samba/
sudo systemctl enable --now smb.service nmb.service
sudo mkdir /var/lib/samba/usershares
sudo groupadd -r sambashare
sudo chown root:sambashare /var/lib/samba/usershares
sudo chmod 1770 /var/lib/samba/usershares
sudo gpasswd sambashare -a $USER
sudo smbpasswd -a $USER

svcenable avahi-daemon.service

exit 0
