#!/bin/bash

echo "Creating swapfile..."
sudo dd if=/dev/zero of=/swapfile bs=1M count=8192 status=progress
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

printf "%s\n" "" "/swapfile none swap defaults 0 0" | sudo tee -a /etc/fstab 
