#!/bin/bash
. ./lib

if (confirm "Would you like to disable WiFi powersave? \n "); then
  clear
	LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
	printf "%s\n" "[connection]" "wifi.powersave = 2" | sudo tee $LOC
	sudo systemctl restart NetworkManager
  message "WiFi powersave disabled. \n "
fi
