#!/bin/bash
. ./lib

if (confirm "Do you wanto install paru ?"); then
	# Paru
	clear
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si --noconfirm
	cd ..
	sudo rm -rf paru
	pressanykey
fi
