#!/bin/bash
. ./lib

options=()
options+=(
  "ttf-jetbrains-mono-nerd" "" on
  "ttf-fantasque-nerd" "" on
  "ttf-ubuntu-nerd" "" on
  "ttf-ubuntu-mono-nerd" "" on
  "ttf-hack-nerd" "" on
  "ttf-firacode-nerd" "" on
)
sel=$(dialog --backtitle "$apptitle" --title "Fonts :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
  # "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  *) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
