#!/bin/bash
. ./lib

options=()
options+=(
	"Applications" ""
  "Fonts" ""
  "Themes" ""
	"Drivers" ""
	"Desktop Environment" ""
)

defaultitem=""
sel=$(dialog --backtitle "$apptitle" --title "Install Menu :" --default-item "$defultitem" --cancel-button "Back" --menu "" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi
sed i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
"Applications") menu install/apps/menu ;;
"Fonts") script install/fonts/fonts ;;
"Themes") script install/themes/themes ;;
"Drivers") menu install/drivers/menu ;;
"Desktop Environment") menu install/de/menu ;;
esac

exit 0
