#!/bin/bash
. ./lib

options=()
options+=(
  "cmatrix" "" off
  "neofetch" "" on
  "mpv" "" on
  "mc" "" on
  "mlocate" "" on
  "fd" "" on
  "ripgrep" "" on
  "btop" "" on
  "nvtop" "" on
  "bat" "" on
  "psutils" "" on
  "xsel" "" on
  "xclip" "" off
  "wl-clipboard" "" on
  "zsh" "" on
  "zsh-completions" "" on
  "lynx" "" off
  "cava" "(AUR)" off
)
sel=$(dialog --backtitle "$apptitle" --title "Console Applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
  # "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "cava") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  *) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
