#!/bin/bash
. ./lib

options=()
options+=(
  "thunar" "" off
  "thunar-volman" "" off
  "thunar-archive-plugin" "" off
  "file-roller" "" off
  "tumbler" "" off
  "dolphin" "" off
  "dolphin-plugins" "" off
  "kdenetwork-filesharing" "" off
  "ffmpegthumbs" "" off
  "ark" "" off
  "krusader" "" off
  "krename" "" off
  "kdiff3" "" off
)
sel=$(dialog --backtitle "$apptitle" --title "File Browsers :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
  *) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
