#!/bin/bash
. ./lib

options=()
options+=(
	"libreoffice-fresh" "" off
	"libreoffice-still" "" off
	"thunar" "" off
	"thunar-volman" "" off
	"thunar-archive-plugin" "" off
	"xfce4-settings" "" off
	"tumbler" "" on
	"dolphin" "" off
	"dolphin-plugins" "" off
	"kdenetwork-filesharing" "" off
	"krusader" "" on
	"krename" "" on
	"kdiff3" "" on
	"ffmpegthumbs" "" off
	"smplayer" "" off
	"smplayer-skins" "" off
	"smplayer-themes" "" off
	"mousepad" "" on
	"piper" "" off
	"steam" "" on
	"heroic-games-launcher-bin" "(AUR)" on
	"isomaster" "(AUR)" off
	"startup-settings-git" "(AUR)" off
)
sel=$(dialog --backtitle "$apptitle" --title "Generic Applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	"isomaster") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"startup-settings-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	"heroic-games-launcher-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"

exit 0
