#!/bin/bash
. ./lib

options=()
options+=(
  "libreoffice-fresh" "" off
  "libreoffice-still" "" off
  "smplayer" "" off
  "smplayer-skins" "" off
  "smplayer-themes" "" off
  "mousepad" "" on
  "piper" "" off
  "bleachbit" "Profile cleaner" off
  "webapp-manager" "(AUR)" on
  "stacer-bin" "(AUR)" off
  "openrgb-bin" "(AUR)" off
  "isomaster" "(AUR)" off
  "startup-settings-git" "(AUR)" off
)
sel=$(dialog --backtitle "$apptitle" --title "Generic Applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
  "webapp-manager") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "stacer-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "openrgb-bin") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "isomaster") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  "startup-settings-git") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
  *) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
