#!/bin/bash
. ./lib

options=()
options+=(
	"gst-plugins-base" "" on
	"gst-plugins-good" "" on
  "gst-plugins-ugly" "" on
  "gst-plugins-bad" "" on
	"gst-plugin-pipewire" "" on
	"gst-libav" "" on
	"libde265" "" on
)
sel=$(dialog --backtitle "$apptitle" --title "Multimedia :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
	"${options[@]}" \
	3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
	exit 1
fi

for itm in $sel; do
	case $itm in
	# "") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')" ;;
	*) pkg="$pkg $(echo $itm | sed 's/"//g')" ;;
	esac
done

instpkg "$pkg" "$aurpkg"
