#!/bin/bash

# Shell
sudo pacman -S --needed edk2-shell
sudo cp /usr/share/edk2-shell/x64/Shell.efi /boot/shellx64.efi
# remove fallback efi
bootctl unlink arch-linux-fallback.efi
# Loader config
printf "%s\n" "timeout  menu-force" "console-mode  max" | sudo tee /boot/loader/loader.conf
# Secure Boot with sbctl
if [[ "$(efivar -d --name 8be4df61-93ca-11d2-aa0d-00e098032b8c-SetupMode)" -eq 1 ]]; then
  echo "Setting up Secure Boot..."
  sbctl create-keys
  sbctl enroll-keys -m
  sbctl sign -s -o /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /usr/lib/systemd/boot/efi/systemd-bootx64.efi
  sbctl sign -s "${default_uki//\"/}"
  sbctl sign -s /boot/shellx64.efi
else
  echo "Not in Secure Boot setup mode. Skipping..."
fi

# To sign automatically after Generating UKI
printf "%s\n" "#!/usr/bin/env bash" "sbctl sign-all" | tee /etc/initcpio/post/uki-sbctl
chmod +x /etc/initcpio/post/uki-sbctl

bootctl update
